/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Spaces API
 * Hospital Spaces management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HospitalSpace
 */
export interface HospitalSpace {
    /**
     * Unique identifier of hospital space
     * @type {string}
     * @memberof HospitalSpace
     */
    id: string;
    /**
     * Room number in hospital building
     * @type {string}
     * @memberof HospitalSpace
     */
    roomNumber: string;
    /**
     * Name of the hospital space
     * @type {string}
     * @memberof HospitalSpace
     */
    name: string;
    /**
     * Type of space (e.g. ambulance, surgery, department)
     * @type {string}
     * @memberof HospitalSpace
     */
    type: string;
    /**
     * Hospital pavilion where space is located
     * @type {string}
     * @memberof HospitalSpace
     */
    pavilion: string;
    /**
     * Building block identifier
     * @type {string}
     * @memberof HospitalSpace
     */
    block: string;
    /**
     * Floor number (0 = ground floor)
     * @type {number}
     * @memberof HospitalSpace
     */
    floor: number;
    /**
     * Area of the space in square meters
     * @type {number}
     * @memberof HospitalSpace
     */
    areaSquareMeters: number;
    /**
     * Operational status of the space
     * @type {string}
     * @memberof HospitalSpace
     */
    status: string;
    /**
     * Material icon identifier for UI display
     * @type {string}
     * @memberof HospitalSpace
     */
    icon: string;
}

/**
 * Check if a given object implements the HospitalSpace interface.
 */
export function instanceOfHospitalSpace(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "roomNumber" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "pavilion" in value;
    isInstance = isInstance && "block" in value;
    isInstance = isInstance && "floor" in value;
    isInstance = isInstance && "areaSquareMeters" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "icon" in value;

    return isInstance;
}

export function HospitalSpaceFromJSON(json: any): HospitalSpace {
    return HospitalSpaceFromJSONTyped(json, false);
}

export function HospitalSpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): HospitalSpace {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roomNumber': json['roomNumber'],
        'name': json['name'],
        'type': json['type'],
        'pavilion': json['pavilion'],
        'block': json['block'],
        'floor': json['floor'],
        'areaSquareMeters': json['areaSquareMeters'],
        'status': json['status'],
        'icon': json['icon'],
    };
}

export function HospitalSpaceToJSON(value?: HospitalSpace | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'roomNumber': value.roomNumber,
        'name': value.name,
        'type': value.type,
        'pavilion': value.pavilion,
        'block': value.block,
        'floor': value.floor,
        'areaSquareMeters': value.areaSquareMeters,
        'status': value.status,
        'icon': value.icon,
    };
}

