/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Spaces API
 * Hospital Spaces management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HospitalSpace,
} from '../models';
import {
    HospitalSpaceFromJSON,
    HospitalSpaceToJSON,
} from '../models';

export interface GetHospitalSpacesEntriesRequest {
    spaceId: string;
}

/**
 * HospitalSpacesListApi - interface
 * 
 * @export
 * @interface HospitalSpacesListApiInterface
 */
export interface HospitalSpacesListApiInterface {
    /**
     * Returns list of hospital spaces (filtered by spaceId context if needed)
     * @summary Provides hospital spaces list
     * @param {string} spaceId Identifier of hospital space group (e.g. hospital / pavilion / facility)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalSpacesListApiInterface
     */
    getHospitalSpacesEntriesRaw(requestParameters: GetHospitalSpacesEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HospitalSpace>>>;

    /**
     * Returns list of hospital spaces (filtered by spaceId context if needed)
     * Provides hospital spaces list
     */
    getHospitalSpacesEntries(requestParameters: GetHospitalSpacesEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HospitalSpace>>;

}

/**
 * 
 */
export class HospitalSpacesListApi extends runtime.BaseAPI implements HospitalSpacesListApiInterface {

    /**
     * Returns list of hospital spaces (filtered by spaceId context if needed)
     * Provides hospital spaces list
     */
    async getHospitalSpacesEntriesRaw(requestParameters: GetHospitalSpacesEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HospitalSpace>>> {
        if (requestParameters.spaceId === null || requestParameters.spaceId === undefined) {
            throw new runtime.RequiredError('spaceId','Required parameter requestParameters.spaceId was null or undefined when calling getHospitalSpacesEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hospital-spaces/{spaceId}/entries`.replace(`{${"spaceId"}}`, encodeURIComponent(String(requestParameters.spaceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HospitalSpaceFromJSON));
    }

    /**
     * Returns list of hospital spaces (filtered by spaceId context if needed)
     * Provides hospital spaces list
     */
    async getHospitalSpacesEntries(requestParameters: GetHospitalSpacesEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HospitalSpace>> {
        const response = await this.getHospitalSpacesEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
