/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LnHospitalSpacesList {
    }
}
declare global {
    interface HTMLLnHospitalSpacesListElement extends Components.LnHospitalSpacesList, HTMLStencilElement {
    }
    var HTMLLnHospitalSpacesListElement: {
        prototype: HTMLLnHospitalSpacesListElement;
        new (): HTMLLnHospitalSpacesListElement;
    };
    interface HTMLElementTagNameMap {
        "ln-hospital-spaces-list": HTMLLnHospitalSpacesListElement;
    }
}
declare namespace LocalJSX {
    interface LnHospitalSpacesList {
    }
    interface IntrinsicElements {
        "ln-hospital-spaces-list": LnHospitalSpacesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ln-hospital-spaces-list": LocalJSX.IntrinsicElements["ln-hospital-spaces-list"] & JSXBase.HTMLAttributes<HTMLLnHospitalSpacesListElement>;
        }
    }
}
